// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/userfollow/userfollow.proto

package userfollow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFollow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowTo      string                 `protobuf:"bytes,2,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollow) Reset() {
	*x = UserFollow{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollow) ProtoMessage() {}

func (x *UserFollow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollow.ProtoReflect.Descriptor instead.
func (*UserFollow) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{0}
}

func (x *UserFollow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollow) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

func (x *UserFollow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowTo      string                 `protobuf:"bytes,2,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserRequest) Reset() {
	*x = FollowUserRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserRequest) ProtoMessage() {}

func (x *FollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserRequest.ProtoReflect.Descriptor instead.
func (*FollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{1}
}

func (x *FollowUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FollowUserRequest) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

type FollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollow    *UserFollow            `protobuf:"bytes,1,opt,name=user_follow,json=userFollow,proto3" json:"user_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowUserResponse) Reset() {
	*x = FollowUserResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowUserResponse) ProtoMessage() {}

func (x *FollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowUserResponse.ProtoReflect.Descriptor instead.
func (*FollowUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{2}
}

func (x *FollowUserResponse) GetUserFollow() *UserFollow {
	if x != nil {
		return x.UserFollow
	}
	return nil
}

type UnfollowUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowTo      string                 `protobuf:"bytes,2,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserRequest) Reset() {
	*x = UnfollowUserRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserRequest) ProtoMessage() {}

func (x *UnfollowUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserRequest.ProtoReflect.Descriptor instead.
func (*UnfollowUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{3}
}

func (x *UnfollowUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnfollowUserRequest) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

type UnfollowUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnfollowUserResponse) Reset() {
	*x = UnfollowUserResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnfollowUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnfollowUserResponse) ProtoMessage() {}

func (x *UnfollowUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnfollowUserResponse.ProtoReflect.Descriptor instead.
func (*UnfollowUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{4}
}

func (x *UnfollowUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FindAllFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowTo      string                 `protobuf:"bytes,1,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllFollowersRequest) Reset() {
	*x = FindAllFollowersRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllFollowersRequest) ProtoMessage() {}

func (x *FindAllFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllFollowersRequest.ProtoReflect.Descriptor instead.
func (*FindAllFollowersRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllFollowersRequest) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

type FindAllFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollows   []*UserFollow          `protobuf:"bytes,1,rep,name=user_follows,json=userFollows,proto3" json:"user_follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllFollowersResponse) Reset() {
	*x = FindAllFollowersResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllFollowersResponse) ProtoMessage() {}

func (x *FindAllFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllFollowersResponse.ProtoReflect.Descriptor instead.
func (*FindAllFollowersResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllFollowersResponse) GetUserFollows() []*UserFollow {
	if x != nil {
		return x.UserFollows
	}
	return nil
}

type FindAllFollowingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllFollowingsRequest) Reset() {
	*x = FindAllFollowingsRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllFollowingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllFollowingsRequest) ProtoMessage() {}

func (x *FindAllFollowingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllFollowingsRequest.ProtoReflect.Descriptor instead.
func (*FindAllFollowingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllFollowingsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllFollowingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollows   []*UserFollow          `protobuf:"bytes,1,rep,name=user_follows,json=userFollows,proto3" json:"user_follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllFollowingsResponse) Reset() {
	*x = FindAllFollowingsResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllFollowingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllFollowingsResponse) ProtoMessage() {}

func (x *FindAllFollowingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllFollowingsResponse.ProtoReflect.Descriptor instead.
func (*FindAllFollowingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllFollowingsResponse) GetUserFollows() []*UserFollow {
	if x != nil {
		return x.UserFollows
	}
	return nil
}

var File_proto_userfollow_userfollow_proto protoreflect.FileDescriptor

const file_proto_userfollow_userfollow_proto_rawDesc = "" +
	"\n" +
	"!proto/userfollow/userfollow.proto\x12\n" +
	"userfollow\"a\n" +
	"\n" +
	"UserFollow\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfollow_to\x18\x02 \x01(\tR\bfollowTo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\tR\tcreatedAt\"I\n" +
	"\x11FollowUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfollow_to\x18\x02 \x01(\tR\bfollowTo\"M\n" +
	"\x12FollowUserResponse\x127\n" +
	"\vuser_follow\x18\x01 \x01(\v2\x16.userfollow.UserFollowR\n" +
	"userFollow\"K\n" +
	"\x13UnfollowUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfollow_to\x18\x02 \x01(\tR\bfollowTo\"0\n" +
	"\x14UnfollowUserResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"6\n" +
	"\x17FindAllFollowersRequest\x12\x1b\n" +
	"\tfollow_to\x18\x01 \x01(\tR\bfollowTo\"U\n" +
	"\x18FindAllFollowersResponse\x129\n" +
	"\fuser_follows\x18\x01 \x03(\v2\x16.userfollow.UserFollowR\vuserFollows\"3\n" +
	"\x18FindAllFollowingsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"V\n" +
	"\x19FindAllFollowingsResponse\x129\n" +
	"\fuser_follows\x18\x01 \x03(\v2\x16.userfollow.UserFollowR\vuserFollows2\xf4\x02\n" +
	"\x11UserFollowService\x12K\n" +
	"\n" +
	"FollowUser\x12\x1d.userfollow.FollowUserRequest\x1a\x1e.userfollow.FollowUserResponse\x12Q\n" +
	"\fUnfollowUser\x12\x1f.userfollow.UnfollowUserRequest\x1a .userfollow.UnfollowUserResponse\x12]\n" +
	"\x10FindAllFollowers\x12#.userfollow.FindAllFollowersRequest\x1a$.userfollow.FindAllFollowersResponse\x12`\n" +
	"\x11FindAllFollowings\x12$.userfollow.FindAllFollowingsRequest\x1a%.userfollow.FindAllFollowingsResponseB\x12Z\x10proto/userfollowb\x06proto3"

var (
	file_proto_userfollow_userfollow_proto_rawDescOnce sync.Once
	file_proto_userfollow_userfollow_proto_rawDescData []byte
)

func file_proto_userfollow_userfollow_proto_rawDescGZIP() []byte {
	file_proto_userfollow_userfollow_proto_rawDescOnce.Do(func() {
		file_proto_userfollow_userfollow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userfollow_userfollow_proto_rawDesc), len(file_proto_userfollow_userfollow_proto_rawDesc)))
	})
	return file_proto_userfollow_userfollow_proto_rawDescData
}

var file_proto_userfollow_userfollow_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_userfollow_userfollow_proto_goTypes = []any{
	(*UserFollow)(nil),                // 0: userfollow.UserFollow
	(*FollowUserRequest)(nil),         // 1: userfollow.FollowUserRequest
	(*FollowUserResponse)(nil),        // 2: userfollow.FollowUserResponse
	(*UnfollowUserRequest)(nil),       // 3: userfollow.UnfollowUserRequest
	(*UnfollowUserResponse)(nil),      // 4: userfollow.UnfollowUserResponse
	(*FindAllFollowersRequest)(nil),   // 5: userfollow.FindAllFollowersRequest
	(*FindAllFollowersResponse)(nil),  // 6: userfollow.FindAllFollowersResponse
	(*FindAllFollowingsRequest)(nil),  // 7: userfollow.FindAllFollowingsRequest
	(*FindAllFollowingsResponse)(nil), // 8: userfollow.FindAllFollowingsResponse
}
var file_proto_userfollow_userfollow_proto_depIdxs = []int32{
	0, // 0: userfollow.FollowUserResponse.user_follow:type_name -> userfollow.UserFollow
	0, // 1: userfollow.FindAllFollowersResponse.user_follows:type_name -> userfollow.UserFollow
	0, // 2: userfollow.FindAllFollowingsResponse.user_follows:type_name -> userfollow.UserFollow
	1, // 3: userfollow.UserFollowService.FollowUser:input_type -> userfollow.FollowUserRequest
	3, // 4: userfollow.UserFollowService.UnfollowUser:input_type -> userfollow.UnfollowUserRequest
	5, // 5: userfollow.UserFollowService.FindAllFollowers:input_type -> userfollow.FindAllFollowersRequest
	7, // 6: userfollow.UserFollowService.FindAllFollowings:input_type -> userfollow.FindAllFollowingsRequest
	2, // 7: userfollow.UserFollowService.FollowUser:output_type -> userfollow.FollowUserResponse
	4, // 8: userfollow.UserFollowService.UnfollowUser:output_type -> userfollow.UnfollowUserResponse
	6, // 9: userfollow.UserFollowService.FindAllFollowers:output_type -> userfollow.FindAllFollowersResponse
	8, // 10: userfollow.UserFollowService.FindAllFollowings:output_type -> userfollow.FindAllFollowingsResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_userfollow_userfollow_proto_init() }
func file_proto_userfollow_userfollow_proto_init() {
	if File_proto_userfollow_userfollow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userfollow_userfollow_proto_rawDesc), len(file_proto_userfollow_userfollow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userfollow_userfollow_proto_goTypes,
		DependencyIndexes: file_proto_userfollow_userfollow_proto_depIdxs,
		MessageInfos:      file_proto_userfollow_userfollow_proto_msgTypes,
	}.Build()
	File_proto_userfollow_userfollow_proto = out.File
	file_proto_userfollow_userfollow_proto_goTypes = nil
	file_proto_userfollow_userfollow_proto_depIdxs = nil
}
