// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/userfollow/userfollow.proto

package userfollow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserFollow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowTo      string                 `protobuf:"bytes,3,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFollow) Reset() {
	*x = UserFollow{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFollow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFollow) ProtoMessage() {}

func (x *UserFollow) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFollow.ProtoReflect.Descriptor instead.
func (*UserFollow) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{0}
}

func (x *UserFollow) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserFollow) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFollow) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

func (x *UserFollow) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type CreateUserFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FollowTo      string                 `protobuf:"bytes,2,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserFollowRequest) Reset() {
	*x = CreateUserFollowRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserFollowRequest) ProtoMessage() {}

func (x *CreateUserFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserFollowRequest.ProtoReflect.Descriptor instead.
func (*CreateUserFollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserFollowRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserFollowRequest) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

type CreateUserFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollow    *UserFollow            `protobuf:"bytes,1,opt,name=user_follow,json=userFollow,proto3" json:"user_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserFollowResponse) Reset() {
	*x = CreateUserFollowResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserFollowResponse) ProtoMessage() {}

func (x *CreateUserFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserFollowResponse.ProtoReflect.Descriptor instead.
func (*CreateUserFollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserFollowResponse) GetUserFollow() *UserFollow {
	if x != nil {
		return x.UserFollow
	}
	return nil
}

type FindUserFollowByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserFollowByIDRequest) Reset() {
	*x = FindUserFollowByIDRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserFollowByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserFollowByIDRequest) ProtoMessage() {}

func (x *FindUserFollowByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserFollowByIDRequest.ProtoReflect.Descriptor instead.
func (*FindUserFollowByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserFollowByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindUserFollowByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollow    *UserFollow            `protobuf:"bytes,1,opt,name=user_follow,json=userFollow,proto3" json:"user_follow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserFollowByIDResponse) Reset() {
	*x = FindUserFollowByIDResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserFollowByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserFollowByIDResponse) ProtoMessage() {}

func (x *FindUserFollowByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserFollowByIDResponse.ProtoReflect.Descriptor instead.
func (*FindUserFollowByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserFollowByIDResponse) GetUserFollow() *UserFollow {
	if x != nil {
		return x.UserFollow
	}
	return nil
}

type FindAllByUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserRequest) Reset() {
	*x = FindAllByUserRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserRequest) ProtoMessage() {}

func (x *FindAllByUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserRequest.ProtoReflect.Descriptor instead.
func (*FindAllByUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type FindAllByUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollows   []*UserFollow          `protobuf:"bytes,1,rep,name=user_follows,json=userFollows,proto3" json:"user_follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByUserResponse) Reset() {
	*x = FindAllByUserResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByUserResponse) ProtoMessage() {}

func (x *FindAllByUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByUserResponse.ProtoReflect.Descriptor instead.
func (*FindAllByUserResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByUserResponse) GetUserFollows() []*UserFollow {
	if x != nil {
		return x.UserFollows
	}
	return nil
}

type FindAllByFollowToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FollowTo      string                 `protobuf:"bytes,1,opt,name=follow_to,json=followTo,proto3" json:"follow_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByFollowToRequest) Reset() {
	*x = FindAllByFollowToRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByFollowToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByFollowToRequest) ProtoMessage() {}

func (x *FindAllByFollowToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByFollowToRequest.ProtoReflect.Descriptor instead.
func (*FindAllByFollowToRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByFollowToRequest) GetFollowTo() string {
	if x != nil {
		return x.FollowTo
	}
	return ""
}

type FindAllByFollowToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollows   []*UserFollow          `protobuf:"bytes,1,rep,name=user_follows,json=userFollows,proto3" json:"user_follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByFollowToResponse) Reset() {
	*x = FindAllByFollowToResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByFollowToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByFollowToResponse) ProtoMessage() {}

func (x *FindAllByFollowToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByFollowToResponse.ProtoReflect.Descriptor instead.
func (*FindAllByFollowToResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllByFollowToResponse) GetUserFollows() []*UserFollow {
	if x != nil {
		return x.UserFollows
	}
	return nil
}

type FindAllUserFollowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserFollowsRequest) Reset() {
	*x = FindAllUserFollowsRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserFollowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserFollowsRequest) ProtoMessage() {}

func (x *FindAllUserFollowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserFollowsRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserFollowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{9}
}

type FindAllUserFollowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserFollows   []*UserFollow          `protobuf:"bytes,1,rep,name=user_follows,json=userFollows,proto3" json:"user_follows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserFollowsResponse) Reset() {
	*x = FindAllUserFollowsResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserFollowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserFollowsResponse) ProtoMessage() {}

func (x *FindAllUserFollowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserFollowsResponse.ProtoReflect.Descriptor instead.
func (*FindAllUserFollowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllUserFollowsResponse) GetUserFollows() []*UserFollow {
	if x != nil {
		return x.UserFollows
	}
	return nil
}

type DeleteUserFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserFollowRequest) Reset() {
	*x = DeleteUserFollowRequest{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserFollowRequest) ProtoMessage() {}

func (x *DeleteUserFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserFollowRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserFollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteUserFollowRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserFollowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserFollowResponse) Reset() {
	*x = DeleteUserFollowResponse{}
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserFollowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserFollowResponse) ProtoMessage() {}

func (x *DeleteUserFollowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userfollow_userfollow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserFollowResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserFollowResponse) Descriptor() ([]byte, []int) {
	return file_proto_userfollow_userfollow_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteUserFollowResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_userfollow_userfollow_proto protoreflect.FileDescriptor

const file_proto_userfollow_userfollow_proto_rawDesc = "" +
	"\n" +
	"!proto/userfollow/userfollow.proto\x12\n" +
	"userfollow\"q\n" +
	"\n" +
	"UserFollow\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfollow_to\x18\x03 \x01(\tR\bfollowTo\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"O\n" +
	"\x17CreateUserFollowRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfollow_to\x18\x02 \x01(\tR\bfollowTo\"S\n" +
	"\x18CreateUserFollowResponse\x127\n" +
	"\vuser_follow\x18\x01 \x01(\v2\x16.userfollow.UserFollowR\n" +
	"userFollow\"+\n" +
	"\x19FindUserFollowByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"U\n" +
	"\x1aFindUserFollowByIDResponse\x127\n" +
	"\vuser_follow\x18\x01 \x01(\v2\x16.userfollow.UserFollowR\n" +
	"userFollow\"/\n" +
	"\x14FindAllByUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"R\n" +
	"\x15FindAllByUserResponse\x129\n" +
	"\fuser_follows\x18\x01 \x03(\v2\x16.userfollow.UserFollowR\vuserFollows\"7\n" +
	"\x18FindAllByFollowToRequest\x12\x1b\n" +
	"\tfollow_to\x18\x01 \x01(\tR\bfollowTo\"V\n" +
	"\x19FindAllByFollowToResponse\x129\n" +
	"\fuser_follows\x18\x01 \x03(\v2\x16.userfollow.UserFollowR\vuserFollows\"\x1b\n" +
	"\x19FindAllUserFollowsRequest\"W\n" +
	"\x1aFindAllUserFollowsResponse\x129\n" +
	"\fuser_follows\x18\x01 \x03(\v2\x16.userfollow.UserFollowR\vuserFollows\")\n" +
	"\x17DeleteUserFollowRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"4\n" +
	"\x18DeleteUserFollowResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xd3\x04\n" +
	"\x11UserFollowService\x12]\n" +
	"\x10CreateUserFollow\x12#.userfollow.CreateUserFollowRequest\x1a$.userfollow.CreateUserFollowResponse\x12c\n" +
	"\x12FindUserFollowByID\x12%.userfollow.FindUserFollowByIDRequest\x1a&.userfollow.FindUserFollowByIDResponse\x12T\n" +
	"\rFindAllByUser\x12 .userfollow.FindAllByUserRequest\x1a!.userfollow.FindAllByUserResponse\x12`\n" +
	"\x11FindAllByFollowTo\x12$.userfollow.FindAllByFollowToRequest\x1a%.userfollow.FindAllByFollowToResponse\x12c\n" +
	"\x12FindAllUserFollows\x12%.userfollow.FindAllUserFollowsRequest\x1a&.userfollow.FindAllUserFollowsResponse\x12]\n" +
	"\x10DeleteUserFollow\x12#.userfollow.DeleteUserFollowRequest\x1a$.userfollow.DeleteUserFollowResponseB\x12Z\x10proto/userfollowb\x06proto3"

var (
	file_proto_userfollow_userfollow_proto_rawDescOnce sync.Once
	file_proto_userfollow_userfollow_proto_rawDescData []byte
)

func file_proto_userfollow_userfollow_proto_rawDescGZIP() []byte {
	file_proto_userfollow_userfollow_proto_rawDescOnce.Do(func() {
		file_proto_userfollow_userfollow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userfollow_userfollow_proto_rawDesc), len(file_proto_userfollow_userfollow_proto_rawDesc)))
	})
	return file_proto_userfollow_userfollow_proto_rawDescData
}

var file_proto_userfollow_userfollow_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_userfollow_userfollow_proto_goTypes = []any{
	(*UserFollow)(nil),                 // 0: userfollow.UserFollow
	(*CreateUserFollowRequest)(nil),    // 1: userfollow.CreateUserFollowRequest
	(*CreateUserFollowResponse)(nil),   // 2: userfollow.CreateUserFollowResponse
	(*FindUserFollowByIDRequest)(nil),  // 3: userfollow.FindUserFollowByIDRequest
	(*FindUserFollowByIDResponse)(nil), // 4: userfollow.FindUserFollowByIDResponse
	(*FindAllByUserRequest)(nil),       // 5: userfollow.FindAllByUserRequest
	(*FindAllByUserResponse)(nil),      // 6: userfollow.FindAllByUserResponse
	(*FindAllByFollowToRequest)(nil),   // 7: userfollow.FindAllByFollowToRequest
	(*FindAllByFollowToResponse)(nil),  // 8: userfollow.FindAllByFollowToResponse
	(*FindAllUserFollowsRequest)(nil),  // 9: userfollow.FindAllUserFollowsRequest
	(*FindAllUserFollowsResponse)(nil), // 10: userfollow.FindAllUserFollowsResponse
	(*DeleteUserFollowRequest)(nil),    // 11: userfollow.DeleteUserFollowRequest
	(*DeleteUserFollowResponse)(nil),   // 12: userfollow.DeleteUserFollowResponse
}
var file_proto_userfollow_userfollow_proto_depIdxs = []int32{
	0,  // 0: userfollow.CreateUserFollowResponse.user_follow:type_name -> userfollow.UserFollow
	0,  // 1: userfollow.FindUserFollowByIDResponse.user_follow:type_name -> userfollow.UserFollow
	0,  // 2: userfollow.FindAllByUserResponse.user_follows:type_name -> userfollow.UserFollow
	0,  // 3: userfollow.FindAllByFollowToResponse.user_follows:type_name -> userfollow.UserFollow
	0,  // 4: userfollow.FindAllUserFollowsResponse.user_follows:type_name -> userfollow.UserFollow
	1,  // 5: userfollow.UserFollowService.CreateUserFollow:input_type -> userfollow.CreateUserFollowRequest
	3,  // 6: userfollow.UserFollowService.FindUserFollowByID:input_type -> userfollow.FindUserFollowByIDRequest
	5,  // 7: userfollow.UserFollowService.FindAllByUser:input_type -> userfollow.FindAllByUserRequest
	7,  // 8: userfollow.UserFollowService.FindAllByFollowTo:input_type -> userfollow.FindAllByFollowToRequest
	9,  // 9: userfollow.UserFollowService.FindAllUserFollows:input_type -> userfollow.FindAllUserFollowsRequest
	11, // 10: userfollow.UserFollowService.DeleteUserFollow:input_type -> userfollow.DeleteUserFollowRequest
	2,  // 11: userfollow.UserFollowService.CreateUserFollow:output_type -> userfollow.CreateUserFollowResponse
	4,  // 12: userfollow.UserFollowService.FindUserFollowByID:output_type -> userfollow.FindUserFollowByIDResponse
	6,  // 13: userfollow.UserFollowService.FindAllByUser:output_type -> userfollow.FindAllByUserResponse
	8,  // 14: userfollow.UserFollowService.FindAllByFollowTo:output_type -> userfollow.FindAllByFollowToResponse
	10, // 15: userfollow.UserFollowService.FindAllUserFollows:output_type -> userfollow.FindAllUserFollowsResponse
	12, // 16: userfollow.UserFollowService.DeleteUserFollow:output_type -> userfollow.DeleteUserFollowResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_userfollow_userfollow_proto_init() }
func file_proto_userfollow_userfollow_proto_init() {
	if File_proto_userfollow_userfollow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userfollow_userfollow_proto_rawDesc), len(file_proto_userfollow_userfollow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userfollow_userfollow_proto_goTypes,
		DependencyIndexes: file_proto_userfollow_userfollow_proto_depIdxs,
		MessageInfos:      file_proto_userfollow_userfollow_proto_msgTypes,
	}.Build()
	File_proto_userfollow_userfollow_proto = out.File
	file_proto_userfollow_userfollow_proto_goTypes = nil
	file_proto_userfollow_userfollow_proto_depIdxs = nil
}
