// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: proto/userreport/userreport.proto

package userreport

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserReport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Reporter      string                 `protobuf:"bytes,2,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo      string                 `protobuf:"bytes,3,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserReport) Reset() {
	*x = UserReport{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserReport) ProtoMessage() {}

func (x *UserReport) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserReport.ProtoReflect.Descriptor instead.
func (*UserReport) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{0}
}

func (x *UserReport) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserReport) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *UserReport) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *UserReport) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *UserReport) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reporter      string                 `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	ReportTo      string                 `protobuf:"bytes,2,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReportRequest) Reset() {
	*x = CreateUserReportRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReportRequest) ProtoMessage() {}

func (x *CreateUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReportRequest.ProtoReflect.Descriptor instead.
func (*CreateUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserReportRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *CreateUserReportRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

func (x *CreateUserReportRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *CreateUserReportRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateUserReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReport    *UserReport            `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserReportResponse) Reset() {
	*x = CreateUserReportResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserReportResponse) ProtoMessage() {}

func (x *CreateUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserReportResponse.ProtoReflect.Descriptor instead.
func (*CreateUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{2}
}

func (x *CreateUserReportResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type FindUserReportByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserReportByIDRequest) Reset() {
	*x = FindUserReportByIDRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserReportByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReportByIDRequest) ProtoMessage() {}

func (x *FindUserReportByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReportByIDRequest.ProtoReflect.Descriptor instead.
func (*FindUserReportByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{3}
}

func (x *FindUserReportByIDRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type FindUserReportByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReport    *UserReport            `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindUserReportByIDResponse) Reset() {
	*x = FindUserReportByIDResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindUserReportByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindUserReportByIDResponse) ProtoMessage() {}

func (x *FindUserReportByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindUserReportByIDResponse.ProtoReflect.Descriptor instead.
func (*FindUserReportByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{4}
}

func (x *FindUserReportByIDResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type FindAllByReporterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reporter      string                 `protobuf:"bytes,1,opt,name=reporter,proto3" json:"reporter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByReporterRequest) Reset() {
	*x = FindAllByReporterRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByReporterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReporterRequest) ProtoMessage() {}

func (x *FindAllByReporterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReporterRequest.ProtoReflect.Descriptor instead.
func (*FindAllByReporterRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{5}
}

func (x *FindAllByReporterRequest) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

type FindAllByReporterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReports   []*UserReport          `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByReporterResponse) Reset() {
	*x = FindAllByReporterResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByReporterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReporterResponse) ProtoMessage() {}

func (x *FindAllByReporterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReporterResponse.ProtoReflect.Descriptor instead.
func (*FindAllByReporterResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{6}
}

func (x *FindAllByReporterResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type FindAllByReportToRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportTo      string                 `protobuf:"bytes,1,opt,name=report_to,json=reportTo,proto3" json:"report_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByReportToRequest) Reset() {
	*x = FindAllByReportToRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByReportToRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReportToRequest) ProtoMessage() {}

func (x *FindAllByReportToRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReportToRequest.ProtoReflect.Descriptor instead.
func (*FindAllByReportToRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{7}
}

func (x *FindAllByReportToRequest) GetReportTo() string {
	if x != nil {
		return x.ReportTo
	}
	return ""
}

type FindAllByReportToResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReports   []*UserReport          `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllByReportToResponse) Reset() {
	*x = FindAllByReportToResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllByReportToResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllByReportToResponse) ProtoMessage() {}

func (x *FindAllByReportToResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllByReportToResponse.ProtoReflect.Descriptor instead.
func (*FindAllByReportToResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{8}
}

func (x *FindAllByReportToResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type FindAllUserReportsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserReportsRequest) Reset() {
	*x = FindAllUserReportsRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserReportsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserReportsRequest) ProtoMessage() {}

func (x *FindAllUserReportsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserReportsRequest.ProtoReflect.Descriptor instead.
func (*FindAllUserReportsRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{9}
}

type FindAllUserReportsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReports   []*UserReport          `protobuf:"bytes,1,rep,name=user_reports,json=userReports,proto3" json:"user_reports,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindAllUserReportsResponse) Reset() {
	*x = FindAllUserReportsResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindAllUserReportsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindAllUserReportsResponse) ProtoMessage() {}

func (x *FindAllUserReportsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindAllUserReportsResponse.ProtoReflect.Descriptor instead.
func (*FindAllUserReportsResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{10}
}

func (x *FindAllUserReportsResponse) GetUserReports() []*UserReport {
	if x != nil {
		return x.UserReports
	}
	return nil
}

type PatchUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Detail        *string                `protobuf:"bytes,2,opt,name=detail,proto3,oneof" json:"detail,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchUserReportRequest) Reset() {
	*x = PatchUserReportRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserReportRequest) ProtoMessage() {}

func (x *PatchUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserReportRequest.ProtoReflect.Descriptor instead.
func (*PatchUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{11}
}

func (x *PatchUserReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PatchUserReportRequest) GetDetail() string {
	if x != nil && x.Detail != nil {
		return *x.Detail
	}
	return ""
}

func (x *PatchUserReportRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

type PatchUserReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserReport    *UserReport            `protobuf:"bytes,1,opt,name=user_report,json=userReport,proto3" json:"user_report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchUserReportResponse) Reset() {
	*x = PatchUserReportResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchUserReportResponse) ProtoMessage() {}

func (x *PatchUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchUserReportResponse.ProtoReflect.Descriptor instead.
func (*PatchUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{12}
}

func (x *PatchUserReportResponse) GetUserReport() *UserReport {
	if x != nil {
		return x.UserReport
	}
	return nil
}

type DeleteUserReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReportRequest) Reset() {
	*x = DeleteUserReportRequest{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportRequest) ProtoMessage() {}

func (x *DeleteUserReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserReportRequest) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserReportRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteUserReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserReportResponse) Reset() {
	*x = DeleteUserReportResponse{}
	mi := &file_proto_userreport_userreport_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserReportResponse) ProtoMessage() {}

func (x *DeleteUserReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_userreport_userreport_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserReportResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserReportResponse) Descriptor() ([]byte, []int) {
	return file_proto_userreport_userreport_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteUserReportResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_userreport_userreport_proto protoreflect.FileDescriptor

const file_proto_userreport_userreport_proto_rawDesc = "" +
	"\n" +
	"!proto/userreport/userreport.proto\x12\n" +
	"userreport\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\n" +
	"UserReport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\breporter\x18\x02 \x01(\tR\breporter\x12\x1b\n" +
	"\treport_to\x18\x03 \x01(\tR\breportTo\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\"\x82\x01\n" +
	"\x17CreateUserReportRequest\x12\x1a\n" +
	"\breporter\x18\x01 \x01(\tR\breporter\x12\x1b\n" +
	"\treport_to\x18\x02 \x01(\tR\breportTo\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\"S\n" +
	"\x18CreateUserReportResponse\x127\n" +
	"\vuser_report\x18\x01 \x01(\v2\x16.userreport.UserReportR\n" +
	"userReport\"+\n" +
	"\x19FindUserReportByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"U\n" +
	"\x1aFindUserReportByIDResponse\x127\n" +
	"\vuser_report\x18\x01 \x01(\v2\x16.userreport.UserReportR\n" +
	"userReport\"6\n" +
	"\x18FindAllByReporterRequest\x12\x1a\n" +
	"\breporter\x18\x01 \x01(\tR\breporter\"V\n" +
	"\x19FindAllByReporterResponse\x129\n" +
	"\fuser_reports\x18\x01 \x03(\v2\x16.userreport.UserReportR\vuserReports\"7\n" +
	"\x18FindAllByReportToRequest\x12\x1b\n" +
	"\treport_to\x18\x01 \x01(\tR\breportTo\"V\n" +
	"\x19FindAllByReportToResponse\x129\n" +
	"\fuser_reports\x18\x01 \x03(\v2\x16.userreport.UserReportR\vuserReports\"\x1b\n" +
	"\x19FindAllUserReportsRequest\"W\n" +
	"\x1aFindAllUserReportsResponse\x129\n" +
	"\fuser_reports\x18\x01 \x03(\v2\x16.userreport.UserReportR\vuserReports\"x\n" +
	"\x16PatchUserReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1b\n" +
	"\x06detail\x18\x02 \x01(\tH\x00R\x06detail\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01B\t\n" +
	"\a_detailB\t\n" +
	"\a_status\"R\n" +
	"\x17PatchUserReportResponse\x127\n" +
	"\vuser_report\x18\x01 \x01(\v2\x16.userreport.UserReportR\n" +
	"userReport\")\n" +
	"\x17DeleteUserReportRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"4\n" +
	"\x18DeleteUserReportResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xbb\x05\n" +
	"\x11UserReportService\x12]\n" +
	"\x10CreateUserReport\x12#.userreport.CreateUserReportRequest\x1a$.userreport.CreateUserReportResponse\x12c\n" +
	"\x12FindUserReportByID\x12%.userreport.FindUserReportByIDRequest\x1a&.userreport.FindUserReportByIDResponse\x12`\n" +
	"\x11FindAllByReporter\x12$.userreport.FindAllByReporterRequest\x1a%.userreport.FindAllByReporterResponse\x12`\n" +
	"\x11FindAllByReportTo\x12$.userreport.FindAllByReportToRequest\x1a%.userreport.FindAllByReportToResponse\x12c\n" +
	"\x12FindAllUserReports\x12%.userreport.FindAllUserReportsRequest\x1a&.userreport.FindAllUserReportsResponse\x12Z\n" +
	"\x0fPatchUserReport\x12\".userreport.PatchUserReportRequest\x1a#.userreport.PatchUserReportResponse\x12]\n" +
	"\x10DeleteUserReport\x12#.userreport.DeleteUserReportRequest\x1a$.userreport.DeleteUserReportResponseB\x12Z\x10proto/userreportb\x06proto3"

var (
	file_proto_userreport_userreport_proto_rawDescOnce sync.Once
	file_proto_userreport_userreport_proto_rawDescData []byte
)

func file_proto_userreport_userreport_proto_rawDescGZIP() []byte {
	file_proto_userreport_userreport_proto_rawDescOnce.Do(func() {
		file_proto_userreport_userreport_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_userreport_userreport_proto_rawDesc), len(file_proto_userreport_userreport_proto_rawDesc)))
	})
	return file_proto_userreport_userreport_proto_rawDescData
}

var file_proto_userreport_userreport_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_userreport_userreport_proto_goTypes = []any{
	(*UserReport)(nil),                 // 0: userreport.UserReport
	(*CreateUserReportRequest)(nil),    // 1: userreport.CreateUserReportRequest
	(*CreateUserReportResponse)(nil),   // 2: userreport.CreateUserReportResponse
	(*FindUserReportByIDRequest)(nil),  // 3: userreport.FindUserReportByIDRequest
	(*FindUserReportByIDResponse)(nil), // 4: userreport.FindUserReportByIDResponse
	(*FindAllByReporterRequest)(nil),   // 5: userreport.FindAllByReporterRequest
	(*FindAllByReporterResponse)(nil),  // 6: userreport.FindAllByReporterResponse
	(*FindAllByReportToRequest)(nil),   // 7: userreport.FindAllByReportToRequest
	(*FindAllByReportToResponse)(nil),  // 8: userreport.FindAllByReportToResponse
	(*FindAllUserReportsRequest)(nil),  // 9: userreport.FindAllUserReportsRequest
	(*FindAllUserReportsResponse)(nil), // 10: userreport.FindAllUserReportsResponse
	(*PatchUserReportRequest)(nil),     // 11: userreport.PatchUserReportRequest
	(*PatchUserReportResponse)(nil),    // 12: userreport.PatchUserReportResponse
	(*DeleteUserReportRequest)(nil),    // 13: userreport.DeleteUserReportRequest
	(*DeleteUserReportResponse)(nil),   // 14: userreport.DeleteUserReportResponse
}
var file_proto_userreport_userreport_proto_depIdxs = []int32{
	0,  // 0: userreport.CreateUserReportResponse.user_report:type_name -> userreport.UserReport
	0,  // 1: userreport.FindUserReportByIDResponse.user_report:type_name -> userreport.UserReport
	0,  // 2: userreport.FindAllByReporterResponse.user_reports:type_name -> userreport.UserReport
	0,  // 3: userreport.FindAllByReportToResponse.user_reports:type_name -> userreport.UserReport
	0,  // 4: userreport.FindAllUserReportsResponse.user_reports:type_name -> userreport.UserReport
	0,  // 5: userreport.PatchUserReportResponse.user_report:type_name -> userreport.UserReport
	1,  // 6: userreport.UserReportService.CreateUserReport:input_type -> userreport.CreateUserReportRequest
	3,  // 7: userreport.UserReportService.FindUserReportByID:input_type -> userreport.FindUserReportByIDRequest
	5,  // 8: userreport.UserReportService.FindAllByReporter:input_type -> userreport.FindAllByReporterRequest
	7,  // 9: userreport.UserReportService.FindAllByReportTo:input_type -> userreport.FindAllByReportToRequest
	9,  // 10: userreport.UserReportService.FindAllUserReports:input_type -> userreport.FindAllUserReportsRequest
	11, // 11: userreport.UserReportService.PatchUserReport:input_type -> userreport.PatchUserReportRequest
	13, // 12: userreport.UserReportService.DeleteUserReport:input_type -> userreport.DeleteUserReportRequest
	2,  // 13: userreport.UserReportService.CreateUserReport:output_type -> userreport.CreateUserReportResponse
	4,  // 14: userreport.UserReportService.FindUserReportByID:output_type -> userreport.FindUserReportByIDResponse
	6,  // 15: userreport.UserReportService.FindAllByReporter:output_type -> userreport.FindAllByReporterResponse
	8,  // 16: userreport.UserReportService.FindAllByReportTo:output_type -> userreport.FindAllByReportToResponse
	10, // 17: userreport.UserReportService.FindAllUserReports:output_type -> userreport.FindAllUserReportsResponse
	12, // 18: userreport.UserReportService.PatchUserReport:output_type -> userreport.PatchUserReportResponse
	14, // 19: userreport.UserReportService.DeleteUserReport:output_type -> userreport.DeleteUserReportResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_userreport_userreport_proto_init() }
func file_proto_userreport_userreport_proto_init() {
	if File_proto_userreport_userreport_proto != nil {
		return
	}
	file_proto_userreport_userreport_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_userreport_userreport_proto_rawDesc), len(file_proto_userreport_userreport_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_userreport_userreport_proto_goTypes,
		DependencyIndexes: file_proto_userreport_userreport_proto_depIdxs,
		MessageInfos:      file_proto_userreport_userreport_proto_msgTypes,
	}.Build()
	File_proto_userreport_userreport_proto = out.File
	file_proto_userreport_userreport_proto_goTypes = nil
	file_proto_userreport_userreport_proto_depIdxs = nil
}
